import { FC } from 'react'
import Head from 'next/head'
import { CatalogView } from '@/views/catalog-view'

const CategoryPage: FC = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
    </Head>
    <CatalogView />
  </div>
)

export default CategoryPage
