import { FC } from 'react'
import Head from 'next/head'
import { CatalogView } from '@/views/catalog-view'
import { dehydrate, QueryClient } from 'react-query'
import { prefetchProductCollection } from '@/entities/product/model/product-collection-query'
import { GetServerSideProps } from 'next'

const CategoryPage: FC = () => (
  <div>
    <Head>
      <title>Catalogue</title>
      <meta name='description' content='Generated by create next app' />
    </Head>
    <CatalogView />
  </div>
)

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const queryClient = new QueryClient()
  await prefetchProductCollection(queryClient)
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

export default CategoryPage
