import Head from 'next/head'
import { HomePage } from '@/views/home-view'
import { fetchProductLanding, ProductLandingResponse } from '@/entities/product/model/product-landing-request'
import { FC } from 'react'

interface HomePageProps {
  data: ProductLandingResponse
}

const Home: FC<HomePageProps> = ({ data }) => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
    </Head>
    <HomePage data={data} />
  </div>
)

export async function getStaticProps() {
  try {
    const data = await fetchProductLanding()
    return {
      props: {
        data: data.data,
      },
    }
  } catch (e) {
    console.error(e)
    return {
      props: {
        data: [],
      },
    }
  }
}

export default Home
